$ErrorActionPreference = 'Stop'
$gpxDir = Join-Path $PSScriptRoot '..\gpx'
$outFile = Join-Path $PSScriptRoot '..\data\trail-data.js'
$decimation = 5

if (-not (Test-Path (Split-Path $outFile))) {
    New-Item -ItemType Directory -Path (Split-Path $outFile) -Force | Out-Null
}

$files = Get-ChildItem $gpxDir -Filter '*.gpx'
$ordered = $files | Sort-Object {
    if ($_.Name -match 'PCT stage (\d+)') { [int]$matches[1] }
    elseif ($_.Name -match 'north exit') { 99999 }
    else { 99998 }
}

$trkptRegex = [regex]'<trkpt\s+lat="([-\d.]+)"\s+lon="([-\d.]+)"'
$segments = New-Object System.Collections.Generic.List[object]
$totalKept = 0
$totalSeen = 0

foreach ($f in $ordered) {
    $content = [System.IO.File]::ReadAllText($f.FullName)
    $stageNum = if ($f.Name -match 'PCT stage (\d+)') { [int]$matches[1] } elseif ($f.Name -match 'north exit') { 101 } else { 0 }

    $points = New-Object System.Collections.Generic.List[string]
    $i = 0
    foreach ($m in $trkptRegex.Matches($content)) {
        if (($i % $decimation) -eq 0) {
            $lat = [math]::Round([double]$m.Groups[1].Value, 5)
            $lon = [math]::Round([double]$m.Groups[2].Value, 5)
            $points.Add("[$lat,$lon]")
            $totalKept++
        }
        $i++
        $totalSeen++
    }
    $segments.Add([pscustomobject]@{ stage = $stageNum; name = $f.BaseName; points = $points })
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// Auto-generated by scripts/build-trail-data.ps1')
[void]$sb.AppendLine('// Source: 101 Outdooractive GPX files (PCT Stage 1..100 + north exit)')
[void]$sb.AppendLine("// Trackpoints sampled 1-in-$decimation : kept $totalKept of $totalSeen")
[void]$sb.AppendLine('window.PCT_TRAIL_SEGMENTS = [')
foreach ($seg in $segments) {
    [void]$sb.Append('  { stage: ')
    [void]$sb.Append($seg.stage)
    [void]$sb.Append(', name: ')
    [void]$sb.Append((ConvertTo-Json $seg.name -Compress))
    [void]$sb.Append(', pts: [')
    [void]$sb.Append([string]::Join(',', $seg.points))
    [void]$sb.AppendLine('] },')
}
[void]$sb.AppendLine('];')

[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

$fi = Get-Item $outFile
Write-Output "Wrote $outFile"
Write-Output "  Segments: $($segments.Count)"
Write-Output "  Points kept: $totalKept (of $totalSeen, 1-in-$decimation)"
Write-Output "  File size: $([math]::Round($fi.Length/1KB,1)) KB"
